### ISSUE TITLE
VPN STATUS

### ISSUE THREAD

**Issue by damienrobins** [Hackplayers/4nonimizer#37] opened 2018-04-15 04:07 UTC
Country:	 use a proxy or VPN that hides this information.</p></div></div></div></section></div></div></div></div><div id="pg-22-5" class="panel-grid panel-has-style"><div class="siteorigin-panels-stretch panel-row-style panel-row-style-for-22-5" style="background-color: #ff7d65;padding: 40px 0; " data-stretch-type="full"><div id="pgc-22-5-0" class="panel-grid-cell"><div id="panel-22-5-0-0" class="so-panel widget panel-first-child panel-last-child" data-index="5"><section id="blog"><div class="row"><div class="large-12 columns"><h3 class="widget-title">Other Resources<div class="row"><div class="large-4 medium-6 small-12 columns"><article class="post"><a href="https://whatismycountry.com/tlds/" title="And another one"><div class="entry-image"><img width="500" height="500" src="https://whatismycountry.com/img/tlds.jpg" class="attachment-intro-thumb size-intro-thumb wp-post-image" alt="Top level domains" /></div><div class="entry-info"><h5 class="entry-title">Top Level Domains</h5></div></a></article></div><div class="large-4 medium-6 small-12 columns"><article class="post"><a href="https://whatismycountry.com/countries/" title="Just a post"><div class="entry-image"><img width="500" height="500" src="https://whatismycountry.com/img/world.png" class="attachment-intro-thumb size-intro-thumb wp-post-image" alt="World map" /></div><div class="entry-info"><h5 class="entry-title">Countries of the World</h5></div></a></article></div><div class="large-4 medium-6 small-12 columns"><article class="post"><a href="" title="Blog post"><div class="entry-image"><img width="500" height="500" src="https://whatismycountry.com/img/thumbs/france-1.jpg" class="attachment-intro-thumb size-intro-thumb wp-post-image" alt="France"  /></div><div class="entry-info"><h5 class="entry-title">France</h5></div></a></article></div></div></div></div></section></div></div></div></div></div></div></div></section><footer id="footer"><div class="row"><div class="large-12 columns text-center"><div><a href="https://whatismycountry.com/privacy/" style="font-size:1.2em; color:white;" title="Privacy policy">Privacy</a></div><div>Copyright 2018 iinix</div></div><a data-scroll href="#top" class="to-top" title="To the top of the page">&#8963;</a></div></footer><link rel="stylesheet" id="intro-body-fonts-css" href="//fonts.googleapis.com/css?family=Raleway%3A400%2C700&#038;ver=4.7.5" type="text/css" media="all" /><noscript><link rel="stylesheet" id="intro-style-css" href="https://whatismycountry.com/style.css" type="text/css" media="all" /></noscript><script type="text/javascript">

done!

**Comment by damienrobins** [comment] 2018-04-15 04:08
wierd thats not what it was supposed to show

**Comment by damienrobins** [comment] 2018-04-15 04:14
trying to figure out how to post this output without the images

**Comment by Hackplayers** [comment] 2018-04-19 16:45
ok, i wait the correct message.

**Comment by damienrobins** [comment] 2018-04-19 16:47
It will not allow me to..



Each time I post..
It truns it into this..
Is there a way I can send you the txt file of the error output?

**Comment by damienrobins** [comment] 2018-04-19 17:11
Also even though it's supposed to be proxychains on, it still will show my original IP in website checkers, including in fb.

**Comment by Hackplayers** [comment] 2018-04-20 07:35
Hello, send me the log to hackplayers at ymail.com

**Comment by damienrobins** [comment] 2018-04-20 22:51
Sent

**Comment by damienrobins** [comment] 2018-04-23 16:35
Any reason why proxychains still leaking dns?

**Comment by Hackplayers** [comment] 2018-04-23 17:06
we've received the data. The problem is that https://whatismycountry.com/ has changed its page and we've to adjust the regex. You can use also geoiplookup to solve the problem now (have you installed it?).

Regarding dns leaks check dnscrypt service.

Regards!

**Comment by vmotos** [comment] 2018-05-02 20:40
Ok, let us work to adapt new regex in https://whatismycountry.com/

**Comment by vmotos** [comment] 2018-05-17 21:33
Fixed in version 1.11

**Closed by vmotos** 2018-05-17 21:33 UTC
